loadfile("./util/lua2cc.lua")() 

network = {
    networkName  = "tinynet",
    createScope  = "tinynet",
    parameterLv  = 0,
    inputLayers  = {"in"},
    outputLayers = {"out"},
    l1   = dwConv2d         ({input = "in",
                              stride = 1, padding = 1}),
    l2   = batchNorm2d      ({}),
    l3   = relu             ({}),
    l4   = pwConv2d         ({}),
    l5   = batchNorm2d      ({}),
    l6   = relu             ({}),
    l7   = dwConv2d         ({stride = 2, padding = 1}),
    l8   = batchNorm2d      ({}),
    l9   = relu             ({}),
    l10  = pwConv2d         ({}),
    l11  = batchNorm2d      ({}),
    l12  = relu             ({}),
    l13  = dwConv2d         ({stride = 1, padding = 1}),
    l14  = batchNorm2d      ({}),
    l15  = relu             ({}),
    l16  = pwConv2d         ({}),
    l17  = batchNorm2d      ({}),
    l18  = relu             ({}),
    l19  = dwConv2d         ({stride = 2, padding = 1}),
    l20  = batchNorm2d      ({}),
    l21  = relu             ({}),
    l22  = pwConv2d         ({}),
    l23  = batchNorm2d      ({}),
    l24  = relu             ({}),
    l25  = dwConv2d         ({stride = 1, padding = 1}),
    l26  = batchNorm2d      ({}),
    l27  = relu             ({}),
    l28  = pwConv2d         ({}),
    l29  = batchNorm2d      ({}),
    l30  = relu             ({}),
    l31  = dwConv2d         ({stride = 2, padding = 1}),
    l32  = batchNorm2d      ({}),
    l33  = relu             ({}),
    l34  = pwConv2d         ({}),
    l35  = batchNorm2d      ({}),
    l36  = relu             ({}),
    l37  = dwConv2d         ({stride = 1, padding = 1}),
    l38  = batchNorm2d      ({}),
    l39  = relu             ({}),
    l40  = pwConv2d         ({}),
    l41  = batchNorm2d      ({}),
    l42  = relu             ({}),
    l43  = maxPool2d        ({stride = 4}),
    l44  = fullyConnected   ({}),
    out  = softmax          ({input = "l44"})
}

ccCodeTranslator(network, {file = "tinynet.c"})
